const portfolioCollectionItems = [
  {
    title: 'Portraits Photography',
    items: [
      {
        imgSrc: '/src/assets/images/portfolio-collections/portraits/1.jpg',
        alt: 'Woman in a blue sweater',
        title: 'Faces of Resilience',
        date: 'March 2022',
        dateTime: '2022-03',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/portraits/2.jpg',
        alt: 'Little girl sitting with a flower crown',
        title: 'Innocence Unveiled',
        date: 'January 2020',
        dateTime: '2020-01',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/portraits/3.jpg',
        alt: 'Woman holding an orange beside her cheek',
        title: 'Elegance in Monochrom',
        date: 'January 2020',
        dateTime: '2020-01',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/portraits/1.jpg',
        alt: 'Woman in a blue sweater',
        title: 'Faces of Resilience',
        date: 'March 2022',
        dateTime: '2022-03',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/portraits/2.jpg',
        alt: 'Little girl sitting with a flower crown',
        title: 'Innocence Unveiled',
        date: 'January 2020',
        dateTime: '2020-01',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/portraits/3.jpg',
        alt: 'Woman holding an orange beside her cheek',
        title: 'Elegance in Monochrom',
        date: 'January 2020',
        dateTime: '2020-01',
      },
    ],
  },
  {
    title: 'Events Photography',
    items: [
      {
        imgSrc: '/src/assets/images/portfolio-collections/events/1.jpg',
        alt: 'Woman wearing a wedding dress',
        title: 'A Wedding Tale',
        date: 'September 2021',
        dateTime: '2021-09',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/events/2.jpg',
        alt: 'Notebook and pen with a man in the background',
        title: 'Corporate Excellence Summit',
        date: 'November 2019',
        dateTime: '2019-11',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/events/3.jpg',
        alt: 'Woman covered in colorful powder at a festival',
        title: 'Festival of Colors',
        date: 'March 2018',
        dateTime: '2018-03',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/events/1.jpg',
        alt: 'Woman wearing a wedding dress',
        title: 'A Wedding Tale',
        date: 'September 2021',
        dateTime: '2021-09',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/events/2.jpg',
        alt: 'Notebook and pen with a man in the background',
        title: 'Corporate Excellence Summit',
        date: 'November 2019',
        dateTime: '2019-11',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/events/3.jpg',
        alt: 'Woman covered in colorful powder at a festival',
        title: 'Festival of Colors',
        date: 'March 2018',
        dateTime: '2018-03',
      },
    ],
  },
  {
    title: 'Commercial Photography',
    items: [
      {
        imgSrc: '/src/assets/images/portfolio-collections/commercial/1.jpg',
        alt: 'Backpack on a rock',
        title: 'Product Elegance',
        date: 'August 2020',
        dateTime: '2020-08',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/commercial/2.jpg',
        alt: '"Collection of playful props including eyes, glasses, teeth and a glove',
        title: 'Brand Storytelling',
        date: 'May 2019',
        dateTime: '2019-05',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/commercial/3.jpg',
        alt: 'Hands chopping fresh herbs',
        title: 'Culinary Delights',
        date: 'February 2017',
        dateTime: '2017-02',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/commercial/1.jpg',
        alt: 'Backpack on a rock',
        title: 'Product Elegance',
        date: 'August 2020',
        dateTime: '2020-08',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/commercial/2.jpg',
        alt: '"Collection of playful props including eyes, glasses, teeth and a glove',
        title: 'Brand Storytelling',
        date: 'May 2019',
        dateTime: '2019-05',
      },
      {
        imgSrc: '/src/assets/images/portfolio-collections/commercial/3.jpg',
        alt: 'Hands chopping fresh herbs',
        title: 'Culinary Delights',
        date: 'February 2017',
        dateTime: '2017-02',
      },
    ],
  },
]

export default portfolioCollectionItems
